local Hostile = require "mob/living/simple_animal/hostile/class"
local Guardian = Hostile:new{
    name = "Guardian Spirit",
    real_name = "Guardian Spirit",
    desc = "A mysterious being that stands by its charge, ever vigilant.",
    speak_emote = {"hisses", },
    gender = "neuter",
    mob_biotypes = {"inorganic", },
    bubble_icon = "guardian",
    response_help = "passes through",
    response_disarm = "flails at",
    response_harm = "punches",
    icon = 'icons/mob/guardian.dmi',
    icon_state = "magicOrange",
    icon_living = "magicOrange",
    icon_dead = "magicOrange",
    speed = 0,
    a_intent = "harm",
    stop_automated_movement = 1,
    movement_type = 2,
    attack_sound = 'sound/weapons/punch1.ogg',
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 0,
    maxbodytemp = 10000000000000000000000000000000,
    attacktext = "punches",
    maxHealth = 10000000000000000000000000000000,
    health = 10000000000000000000000000000000,
    healable = 0,
    damage_coeff = {"brute", "fire", "tox", "clone", "stamina", "oxy", },
    environment_smash = 1,
    obj_damage = 40,
    melee_damage_lower = 15,
    melee_damage_upper = 15,
    butcher_results = {nil, },
    AIStatus = 3,
    hud_type = nil,
    dextrous_hud_type = nil,
    guardian_overlays = nil,
    reset = 0,
    cooldown = 0,
    summoner = nil,
    range = 10,
    toggle_button_type = nil,
    namedatum = nil,
    playstyle_string = "<span class='holoparasite bold'>You are a standard Guardian. You shouldn't exist!</span>",
    magic_fluff_string = "<span class='holoparasite'>You draw the Coder, symbolizing bugs and errors. This shouldn't happen! Submit a bug report!</span>",
    tech_fluff_string = "<span class='holoparasite'>BOOT SEQUENCE COMPLETE. ERROR MODULE LOADED. THIS SHOULDN'T HAPPEN. Submit a bug report!</span>",
    carp_fluff_string = "<span class='holoparasite'>CARP CARP CARP SOME SORT OF HORRIFIC BUG BLAME THE CODERS CARP CARP CARP</span>",

}
return Guardian
