local Megafauna = require "mob/living/simple_animal/hostile/megafauna/class"
local BloodDrunkMiner = Megafauna:new{
    name = "blood-drunk miner",
    desc = "A miner destined to wander forever, engaged in an endless hunt.",
    health = 900,
    maxHealth = 900,
    icon_state = "miner",
    icon_living = "miner",
    icon = 'icons/mob/broadMobs.dmi',
    mob_biotypes = {"organic", "humanoid", },
    light_color = "#E4C7C5",
    movement_type = 1,
    speak_emote = {"roars", },
    speed = 1,
    move_to_delay = 3,
    projectiletype = nil,
    projectilesound = 'sound/weapons/kenetic_accel.ogg',
    ranged = 1,
    ranged_cooldown_time = 16,
    pixel_x = -16,
    crusher_loot = {nil, nil, nil, },
    loot = {nil, nil, },
    wander = 0,
    del_on_death = 1,
    blood_volume = 560,
    internal_type = nil,
    medal_type = "Blood-drunk Miner",
    miner_saw = nil,
    time_until_next_transform = 0,
    dashing = 0,
    dash_cooldown = 15,
    guidance = 0,
    deathmessage = "falls to the ground, decaying into glowing particles.",
    deathsound = "bodyfall",
    do_footstep = 1,

}
return BloodDrunkMiner
