local Hostile = require "mob/living/simple_animal/hostile/class"
local Morph = Hostile:new{
    name = "morph",
    real_name = "morph",
    desc = "A revolting, pulsating pile of flesh.",
    speak_emote = {"gurgles", },
    emote_hear = {"gurgles", },
    icon = 'icons/mob/animal.dmi',
    icon_state = "morph",
    icon_living = "morph",
    icon_dead = "morph_dead",
    speed = 2,
    a_intent = "harm",
    stop_automated_movement = 1,
    status_flags = 8,
    pass_flags = 1,
    ventcrawler = 2,
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 0,
    maxHealth = 150,
    health = 150,
    healable = 0,
    obj_damage = 50,
    melee_damage_lower = 20,
    melee_damage_upper = 20,
    see_in_dark = 8,
    lighting_alpha = 128,
    vision_range = 1,
    wander = 0,
    attacktext = "glomps",
    attack_sound = 'sound/effects/blobattack.ogg',
    butcher_results = {nil, },
    morphed = 0,
    melee_damage_disguised = 0,
    eat_while_disguised = 0,
    form = nil,
    morph_time = 0,
    blacklist_typecache = nil,
    playstyle_string = "<span class='big bold'>You are a morph,</span></b> an abomination of science created primarily with changeling cells. You may take the form of anything nearby by shift-clicking it. This process will alert any nearby observers, and can only be performed once every five seconds. While morphed, you move faster, but do less damage. In addition, anyone within three tiles will note an uncanny wrongness if examining you. You can attack any item or dead creature to consume it - creatures will restore your health. Finally, you can restore yourself to your original form while morphed by shift-clicking yourself.</b>",

}
return Morph
