local Self = require "datum.uplink_item.role_restricted.class"
return {
    CLASS = Self,
    reverse_revolver = require "datum.uplink_item.role_restricted.reverse_revolver.mod",
    reverse_bear_trap = require "datum.uplink_item.role_restricted.reverse_bear_trap.mod",
    chemical_gun = require "datum.uplink_item.role_restricted.chemical_gun.mod",
    modified_syringe_gun = require "datum.uplink_item.role_restricted.modified_syringe_gun.mod",
    magillitis_serum = require "datum.uplink_item.role_restricted.magillitis_serum.mod",
    pressure_mod = require "datum.uplink_item.role_restricted.pressure_mod.mod",
    mimery = require "datum.uplink_item.role_restricted.mimery.mod",
    ez_clean_bundle = require "datum.uplink_item.role_restricted.ez_clean_bundle.mod",
    explosive_hot_potato = require "datum.uplink_item.role_restricted.explosive_hot_potato.mod",
    his_grace = require "datum.uplink_item.role_restricted.his_grace.mod",
    haunted_magic_eightball = require "datum.uplink_item.role_restricted.haunted_magic_eightball.mod",
    concealed_weapon_bay = require "datum.uplink_item.role_restricted.concealed_weapon_bay.mod",
    clowncar = require "datum.uplink_item.role_restricted.clowncar.mod",
    clown_bomb = require "datum.uplink_item.role_restricted.clown_bomb.mod",
    brainwash_disk = require "datum.uplink_item.role_restricted.brainwash_disk.mod",
    gorillacubes = require "datum.uplink_item.role_restricted.gorillacubes.mod",
    blastcannon = require "datum.uplink_item.role_restricted.blastcannon.mod",
    pie_cannon = require "datum.uplink_item.role_restricted.pie_cannon.mod",
    oldtoolboxclean = require "datum.uplink_item.role_restricted.oldtoolboxclean.mod",
    ancient_jumpsuit = require "datum.uplink_item.role_restricted.ancient_jumpsuit.mod",
}
