local Datum = require "datum/class"
local Weather = Datum:new{
    name = "space wind",
    desc = "Heavy gusts of wind blanket the area, periodically knocking down anyone caught in the open.",
    telegraph_message = "<span class='warning'>The wind begins to pick up.</span>",
    telegraph_duration = 300,
    telegraph_sound = nil,
    telegraph_overlay = nil,
    weather_message = "<span class='userdanger'>The wind begins to blow ferociously!</span>",
    weather_duration = 1200,
    weather_duration_lower = 1200,
    weather_duration_upper = 1500,
    weather_sound = nil,
    weather_overlay = nil,
    weather_color = nil,
    end_message = "<span class='danger'>The wind relents its assault.</span>",
    end_duration = 300,
    end_sound = nil,
    end_overlay = nil,
    area_type = nil,
    impacted_areas = {},
    protected_areas = {},
    impacted_z_levels = nil,
    overlay_layer = 10,
    overlay_plane = 0,
    aesthetic = 0,
    immunity_type = "storm",
    stage = 4,
    probability = 0,
    target_trait = "Station",
    barometer_predictable = 0,
    next_hit_time = 0,

}
return Weather
