[package]
name = "ss14"
version = "0.1.0"
authors = ["Hugo Laloge <hugo.laloge@gmail.com>"]
edition = "2018"

[dependencies]
amethyst-byond = { path = "amethyst-byond" }
byond-lua = { path = "byond-lua" }
dmm = { git = "https://github.com/Hugal31/DMM.git" }
dmm-format = { git = "https://github.com/Hugal31/DMM.git" }
fnv = "1"
log = "0.4"
serde = { version ="1", features = ["derive"] }

[dependencies.amethyst]
version = "0.11"
features = ["nightly", "vulkan"]

[features]
default = ["no-slow-safety-check"]
no-slow-safety-check = ["amethyst/no-slow-safety-checks"]

[profile.dev]
opt-level = 2
lto = false
overflow-checks = false
