local Bot = require "mob/living/simple_animal/bot/class"
local Mulebot = Bot:new{
    name = [[\improper MULEbot]],
    desc = "A Multiple Utility Load Effector bot.",
    icon_state = "mulebot0",
    density = true,
    move_resist = 2000,
    animate_movement = 1,
    health = 50,
    maxHealth = 50,
    damage_coeff = {"brute", "fire", "tox", "clone", "stamina", "oxy", },
    a_intent = "harm",
    buckle_lying = 0,
    mob_size = 3,
    radio_key = nil,
    radio_channel = "Supply",
    bot_type = 2,
    model = "MULE",
    bot_core_type = nil,
    id = nil,
    path_image_color = "#7F5200",
    load = nil,
    passenger = nil,
    target = nil,
    loaddir = 0,
    home_destination = "",
    reached_target = 1,
    auto_return = 1,
    auto_pickup = 1,
    report_delivery = 1,
    cell = nil,
    bloodiness = 0,

}
return Mulebot
