local Hostile = require "mob/living/simple_animal/hostile/class"
local Carp = Hostile:new{
    name = "space carp",
    desc = "A ferocious, fang-bearing creature that resembles a fish.",
    icon_state = "carp",
    icon_living = "carp",
    icon_dead = "carp_dead",
    icon_gib = "carp_gib",
    mob_biotypes = {"organic", "beast", },
    speak_chance = 0,
    turns_per_move = 5,
    butcher_results = {nil, },
    response_help = "pets",
    response_disarm = "gently pushes aside",
    response_harm = "hits",
    emote_taunt = {"gnashes", },
    taunt_chance = 30,
    speed = 0,
    maxHealth = 25,
    health = 25,
    spacewalk = 1,
    harm_intent_damage = 8,
    obj_damage = 50,
    melee_damage_lower = 15,
    melee_damage_upper = 15,
    attacktext = "bites",
    attack_sound = 'sound/weapons/bite.ogg',
    speak_emote = {"gnashes", },
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 0,
    maxbodytemp = 1500,
    faction = {"carp", },
    movement_type = 2,
    pressure_resistance = 200,
    gold_core_spawnable = 1,

}
return Carp
