local Self = require "datum.spellbook_entry.item.class"
return {
    CLASS = Self,
    warpwhistle = require "datum.spellbook_entry.item.warpwhistle.mod",
    battlemage_charge = require "datum.spellbook_entry.item.battlemage_charge.mod",
    battlemage = require "datum.spellbook_entry.item.battlemage.mod",
    singularity_hammer = require "datum.spellbook_entry.item.singularity_hammer.mod",
    mjolnir = require "datum.spellbook_entry.item.mjolnir.mod",
    hugbottle = require "datum.spellbook_entry.item.hugbottle.mod",
    bloodbottle = require "datum.spellbook_entry.item.bloodbottle.mod",
    guardian = require "datum.spellbook_entry.item.guardian.mod",
    contract = require "datum.spellbook_entry.item.contract.mod",
    armor = require "datum.spellbook_entry.item.armor.mod",
    wands = require "datum.spellbook_entry.item.wands.mod",
    necrostone = require "datum.spellbook_entry.item.necrostone.mod",
    soulstones = require "datum.spellbook_entry.item.soulstones.mod",
    scryingorb = require "datum.spellbook_entry.item.scryingorb.mod",
    lockerstaff = require "datum.spellbook_entry.item.lockerstaff.mod",
    staffhealing = require "datum.spellbook_entry.item.staffhealing.mod",
    staffdoor = require "datum.spellbook_entry.item.staffdoor.mod",
    spellblade = require "datum.spellbook_entry.item.spellblade.mod",
    staffchaos = require "datum.spellbook_entry.item.staffchaos.mod",
    staffanimation = require "datum.spellbook_entry.item.staffanimation.mod",
    staffchange = require "datum.spellbook_entry.item.staffchange.mod",
}
