local Hostile = require "mob/living/simple_animal/hostile/class"
local Nanotrasen = Hostile:new{
    name = "Nanotrasen Private Security Officer",
    desc = "An officer part of Nanotrasen's private security force, he seems rather unpleased to meet you.",
    icon = 'icons/mob/simple_human.dmi',
    icon_state = "nanotrasen",
    icon_living = "nanotrasen",
    icon_dead = nil,
    icon_gib = "syndicate_gib",
    mob_biotypes = {"organic", "humanoid", },
    speak_chance = 12,
    turns_per_move = 5,
    response_help = "pokes",
    response_disarm = "shoves",
    response_harm = "hits",
    speed = 0,
    stat_attack = 2,
    robust_searching = 1,
    maxHealth = 100,
    health = 100,
    harm_intent_damage = 5,
    melee_damage_lower = 10,
    melee_damage_upper = 15,
    attacktext = "punches",
    attack_sound = 'sound/weapons/punch1.ogg',
    a_intent = "harm",
    loot = {nil, },
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    unsuitable_atmos_damage = 15,
    faction = {"nanotrasenprivate", },
    status_flags = 8,
    speak = {"Stop resisting!", "I AM THE LAW!", "Face the wrath of the golden bolt!", "Stop breaking the law, asshole!", },
    search_objects = 1,
    do_footstep = 1,

}
return Nanotrasen
