local Carbon = require "mob/living/carbon/class"
local Monkey = Carbon:new{
    aggressive = 0,
    frustration = 0,
    pickupTimer = 0,
    enemies = {},
    target = nil,
    pickupTarget = nil,
    mode = 0,
    myPath = {},
    blacklistItems = {},
    maxStepsTick = 6,
    best_force = 0,
    martial_art = nil,
    resisting = 0,
    pickpocketing = 0,
    disposing_body = 0,
    bodyDisposal = nil,
    next_battle_screech = 0,
    battle_screech_cooldown = 50,
    name = "monkey",
    verb_say = "chimpers",
    initial_language_holder = nil,
    icon = 'icons/mob/monkey.dmi',
    icon_state = "monkey1",
    gender = "neuter",
    pass_flags = 1,
    ventcrawler = 1,
    mob_biotypes = {"organic", "humanoid", },
    butcher_results = {nil, nil, },
    type_of_meat = nil,
    gib_type = nil,
    unique_name = 1,
    bodyparts = {nil, nil, nil, nil, nil, nil, },
    hud_type = nil,

}
return Monkey
