local Hostile = require "mob/living/simple_animal/hostile/class"
local BigLegion = Hostile:new{
    name = "legion",
    desc = "One of many.",
    icon = 'icons/mob/lavaland/64x64megafauna.dmi',
    icon_state = "legion",
    icon_living = "legion",
    icon_dead = "legion",
    health = 450,
    maxHealth = 450,
    melee_damage_lower = 20,
    melee_damage_upper = 20,
    anchored = 0,
    AIStatus = 1,
    stop_automated_movement = 0,
    wander = 1,
    maxbodytemp = 10000000000000000000000000000000,
    layer = 4,
    del_on_death = 1,
    sentience_type = 5,
    loot = {nil, nil, },
    move_to_delay = 14,
    vision_range = 5,
    aggro_vision_range = 9,
    speed = 3,
    faction = {"mining", },
    weather_immunities = {"lava", "ash", },
    obj_damage = 30,
    environment_smash = 1,
    see_in_dark = 8,
    lighting_alpha = 128,

}
return BigLegion
