local Self = require "datum.action.class"
return {
    CLASS = Self,
    vehicle = require "datum.action.vehicle.mod",
    peepholeCancel = require "datum.action.peepholeCancel.mod",
    toggle_scope_zoom = require "datum.action.toggle_scope_zoom.mod",
    boss = require "datum.action.boss.mod",
    chameleon_outfit = require "datum.action.chameleon_outfit.mod",
    changeling = require "datum.action.changeling.mod",
    turret_quit = require "datum.action.turret_quit.mod",
    turret_toggle = require "datum.action.turret_toggle.mod",
    drop = require "datum.action.drop.mod",
    strike = require "datum.action.strike.mod",
    kick = require "datum.action.kick.mod",
    throw_wrassle = require "datum.action.throw_wrassle.mod",
    slam = require "datum.action.slam.mod",
    lung_punch = require "datum.action.lung_punch.mod",
    leg_sweep = require "datum.action.leg_sweep.mod",
    neck_chop = require "datum.action.neck_chop.mod",
    small_sprite = require "datum.action.small_sprite.mod",
    language_menu = require "datum.action.language_menu.mod",
    cooldown = require "datum.action.cooldown.mod",
    spell_action = require "datum.action.spell_action.mod",
    item_action = require "datum.action.item_action.mod",
    vote = require "datum.action.vote.mod",
    innate = require "datum.action.innate.mod",
    report = require "datum.action.report.mod",
}
