local SimpleAnimal = require "mob/living/simple_animal/class"
local Slaughter = SimpleAnimal:new{
    name = "slaughter demon",
    real_name = "slaughter demon",
    desc = "A large, menacing creature covered in armored black scales.",
    speak_emote = {"gurgles", },
    emote_hear = {"wails", "screeches", },
    response_help = "thinks better of touching",
    response_disarm = "flails at",
    response_harm = "punches",
    icon = 'icons/mob/mob.dmi',
    icon_state = "daemon",
    icon_living = "daemon",
    mob_biotypes = {"organic", "humanoid", },
    speed = 1,
    a_intent = "harm",
    stop_automated_movement = 1,
    status_flags = 8,
    attack_sound = 'sound/magic/demon_attack1.ogg',
    feast_sound = 'sound/magic/demon_consume.ogg',
    deathsound = 'sound/magic/demon_dies.ogg',
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 0,
    maxbodytemp = 10000000000000000000000000000000,
    faction = {"slaughter", },
    attacktext = "wildly tears into",
    maxHealth = 200,
    health = 200,
    healable = 0,
    environment_smash = 1,
    obj_damage = 50,
    melee_damage_lower = 30,
    melee_damage_upper = 30,
    see_in_dark = 8,
    lighting_alpha = 128,
    bloodcrawl = 2,
    playstyle_string = [[<span class='big bold'>You are a slaughter demon,</span><B> a terrible creature from another realm. You have a single desire: To kill.  You may use the \"Blood Crawl\" ability near blood pools to travel through them, appearing and disappearing from the station at will. Pulling a dead or unconscious mob while you enter a pool will pull them in with you, allowing you to feast and regain your health. You move quickly upon leaving a pool of blood, but the material world will soon sap your strength and leave you sluggish. </B>]],
    loot = {nil, nil, nil, },
    del_on_death = 1,
    deathmessage = "screams in anger as it collapses into a puddle of viscera!",

}
return Slaughter
