local Self = require "datum.ai_laws.class"
return {
    CLASS = Self,
    pai = require "datum.ai_laws.pai.mod",
    custom = require "datum.ai_laws.custom.mod",
    overlord = require "datum.ai_laws.overlord.mod",
    hulkamania = require "datum.ai_laws.hulkamania.mod",
    ratvar = require "datum.ai_laws.ratvar.mod",
    toupee = require "datum.ai_laws.toupee.mod",
    balance = require "datum.ai_laws.balance.mod",
    reporter = require "datum.ai_laws.reporter.mod",
    peacekeeper = require "datum.ai_laws.peacekeeper.mod",
    liveandletlive = require "datum.ai_laws.liveandletlive.mod",
    drone = require "datum.ai_laws.drone.mod",
    maintain = require "datum.ai_laws.maintain.mod",
    hippocratic = require "datum.ai_laws.hippocratic.mod",
    thermodynamic = require "datum.ai_laws.thermodynamic.mod",
    asimovpp = require "datum.ai_laws.asimovpp.mod",
    antimov = require "datum.ai_laws.antimov.mod",
    ninja_override = require "datum.ai_laws.ninja_override.mod",
    syndicate_override = require "datum.ai_laws.syndicate_override.mod",
    malfunction = require "datum.ai_laws.malfunction.mod",
    robocop = require "datum.ai_laws.robocop.mod",
    tyrant = require "datum.ai_laws.tyrant.mod",
    paladin5 = require "datum.ai_laws.paladin5.mod",
    default = require "datum.ai_laws.default.mod",
}
