local Pet = require "mob/living/simple_animal/pet/class"
local Cat = Pet:new{
    name = "cat",
    desc = "Kitty!!",
    icon = 'icons/mob/pets.dmi',
    icon_state = "cat2",
    icon_living = "cat2",
    icon_dead = "cat2_dead",
    gender = "male",
    speak = {"Meow!", "Esp!", "Purr!", "HSSSSS", },
    speak_emote = {"purrs", "meows", },
    emote_hear = {"meows.", "mews.", },
    emote_see = {"shakes its head.", "shivers.", },
    speak_chance = 1,
    turns_per_move = 5,
    see_in_dark = 6,
    ventcrawler = 2,
    pass_flags = 1,
    mob_size = 1,
    mob_biotypes = {"organic", "beast", },
    minbodytemp = 200,
    maxbodytemp = 400,
    unsuitable_atmos_damage = 1,
    animal_species = nil,
    childtype = {nil, },
    butcher_results = {nil, nil, nil, },
    response_help = "pets",
    response_disarm = "gently pushes aside",
    response_harm = "kicks",
    turns_since_scan = 0,
    movement_target = nil,
    gold_core_spawnable = 2,
    collar_type = "cat",
    do_footstep = 1,

}
return Cat
