local Asteroid = require "mob/living/simple_animal/hostile/asteroid/class"
local Basilisk = Asteroid:new{
    name = "basilisk",
    desc = "A territorial beast, covered in a thick shell that absorbs energy. Its stare causes victims to freeze from the inside.",
    icon = 'icons/mob/lavaland/lavaland_monsters.dmi',
    icon_state = "Basilisk",
    icon_living = "Basilisk",
    icon_aggro = "Basilisk_alert",
    icon_dead = "Basilisk_dead",
    icon_gib = "syndicate_gib",
    mob_biotypes = {"organic", "beast", },
    move_to_delay = 20,
    projectiletype = nil,
    projectilesound = 'sound/weapons/pierce.ogg',
    ranged = 1,
    ranged_message = "stares",
    ranged_cooldown_time = 30,
    throw_message = "does nothing against the hard shell of",
    vision_range = 2,
    speed = 3,
    maxHealth = 200,
    health = 200,
    harm_intent_damage = 5,
    obj_damage = 60,
    melee_damage_lower = 12,
    melee_damage_upper = 12,
    attacktext = "bites into",
    a_intent = "harm",
    speak_emote = {"chitters", },
    attack_sound = 'sound/weapons/bladeslice.ogg',
    aggro_vision_range = 9,
    turns_per_move = 5,
    gold_core_spawnable = 1,
    loot = {nil, nil, },

}
return Basilisk
