local Megafauna = require "mob/living/simple_animal/hostile/megafauna/class"
local Legion = Megafauna:new{
    name = "Legion",
    health = 800,
    maxHealth = 800,
    spacewalk = 1,
    icon_state = "legion",
    icon_living = "legion",
    desc = "One of many.",
    icon = 'icons/mob/lavaland/legion.dmi',
    attacktext = "chomps",
    attack_sound = 'sound/magic/demon_attack1.ogg',
    speak_emote = {"echoes", },
    armour_penetration = 50,
    melee_damage_lower = 25,
    melee_damage_upper = 25,
    speed = 2,
    ranged = 1,
    del_on_death = 1,
    retreat_distance = 5,
    minimum_distance = 5,
    ranged_cooldown_time = 20,
    size = 5,
    charging = 0,
    internal_type = nil,
    medal_type = "Legion",
    score_type = "Legion Killed",
    pixel_y = -90,
    pixel_x = -75,
    loot = {nil, },
    vision_range = 13,
    wander = 0,
    elimination = 1,
    appearance_flags = 0,
    mouse_opacity = 1,

}
return Legion
