local Self = require "datum.species.class"
return {
    CLASS = Self,
    krokodil_addict = require "datum.species.krokodil_addict.mod",
    zombie = require "datum.species.zombie.mod",
    vampire = require "datum.species.vampire.mod",
    synth = require "datum.species.synth.mod",
    snail = require "datum.species.snail.mod",
    skeleton = require "datum.species.skeleton.mod",
    shadow = require "datum.species.shadow.mod",
    pod = require "datum.species.pod.mod",
    plasmaman = require "datum.species.plasmaman.mod",
    mush = require "datum.species.mush.mod",
    moth = require "datum.species.moth.mod",
    lizard = require "datum.species.lizard.mod",
    jelly = require "datum.species.jelly.mod",
    golem = require "datum.species.golem.mod",
    fly = require "datum.species.fly.mod",
    human = require "datum.species.human.mod",
    ethereal = require "datum.species.ethereal.mod",
    dullahan = require "datum.species.dullahan.mod",
    corporate = require "datum.species.corporate.mod",
    angel = require "datum.species.angel.mod",
    android = require "datum.species.android.mod",
    abductor = require "datum.species.abductor.mod",
}
