local Self = require "datum.disease.class"
return {
    CLASS = Self,
    revblight = require "datum.disease.revblight.mod",
    advance = require "datum.disease.advance.mod",
    wizarditis = require "datum.disease.wizarditis.mod",
    tuberculosis = require "datum.disease.tuberculosis.mod",
    transformation = require "datum.disease.transformation.mod",
    rhumba_beat = require "datum.disease.rhumba_beat.mod",
    dna_retrovirus = require "datum.disease.dna_retrovirus.mod",
    pierrot_throat = require "datum.disease.pierrot_throat.mod",
    parrot_possession = require "datum.disease.parrot_possession.mod",
    magnitis = require "datum.disease.magnitis.mod",
    heart_failure = require "datum.disease.heart_failure.mod",
    gbs = require "datum.disease.gbs.mod",
    gastrolosis = require "datum.disease.gastrolosis.mod",
    fluspanish = require "datum.disease.fluspanish.mod",
    flu = require "datum.disease.flu.mod",
    fake_gbs = require "datum.disease.fake_gbs.mod",
    dnaspread = require "datum.disease.dnaspread.mod",
    decloning = require "datum.disease.decloning.mod",
    cold9 = require "datum.disease.cold9.mod",
    cold = require "datum.disease.cold.mod",
    brainrot = require "datum.disease.brainrot.mod",
    beesease = require "datum.disease.beesease.mod",
    appendicitis = require "datum.disease.appendicitis.mod",
    anxiety = require "datum.disease.anxiety.mod",
}
