local Drone = require "mob/living/simple_animal/drone/class"
local Cogscarab = Drone:new{
    name = "cogscarab",
    desc = "A strange, drone-like machine. It constantly emits the hum of gears.",
    icon_state = "drone_clock",
    icon_living = "drone_clock",
    icon_dead = "drone_clock_dead",
    picked = 1,
    pass_flags = 1,
    health = 50,
    maxHealth = 50,
    harm_intent_damage = 5,
    density = true,
    speed = 1,
    ventcrawler = 0,
    faction = {"neutral", "ratvar", },
    speak_emote = {"clanks", "clinks", "clunks", "clangs", },
    verb_ask = "requests",
    verb_exclaim = "proclaims",
    verb_whisper = "imparts",
    verb_yell = "harangues",
    bubble_icon = "clock",
    initial_language_holder = nil,
    light_color = "#E42742",
    heavy_emp_damage = 0,
    laws = "0. Purge all untruths and honor Ratvar.",
    default_storage = nil,
    hacked = 1,
    visualAppearence = "drone_clock",
    can_be_held = 0,
    flavortext = "<b><span class='nezbere'>You are a cogscarab,</span> a tiny building construct of Ratvar. While you're weak and can't recite scripture, you have a set of quick tools, as well as a replica fabricator that can create brass and convert objects.<br><br>Work with the servants of Ratvar to construct and maintain defenses at the City of Cogs. If there are no servants, use this time to experiment with base designs!",

}
return Cogscarab
