local SimpleAnimal = require "mob/living/simple_animal/class"
local Shade = SimpleAnimal:new{
    name = "Shade",
    real_name = "Shade",
    desc = "A bound spirit.",
    gender = "plural",
    icon = 'icons/mob/mob.dmi',
    icon_state = "shade",
    icon_living = "shade",
    mob_biotypes = {"spirit", },
    maxHealth = 40,
    health = 40,
    spacewalk = 1,
    healable = 0,
    speak_emote = {"hisses", },
    emote_hear = {"wails.", "screeches.", },
    response_help = "puts their hand through",
    response_disarm = "flails at",
    response_harm = "punches",
    speak_chance = 1,
    melee_damage_lower = 5,
    melee_damage_upper = 12,
    attacktext = "metaphysically strikes",
    minbodytemp = 0,
    maxbodytemp = 10000000000000000000000000000000,
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    stop_automated_movement = 1,
    status_flags = 8,
    faction = {"cult", },
    movement_type = 2,
    loot = {nil, },
    del_on_death = 1,
    initial_language_holder = nil,

}
return Shade
