local Self = require "turf.open.floor.class"
return {
    CLASS = Self,
    holofloor = require "turf.open.floor.holofloor.mod",
    engine = require "turf.open.floor.engine.mod",
    plasteel = require "turf.open.floor.plasteel.mod",
    black = require "turf.open.floor.black.mod",
    white = require "turf.open.floor.white.mod",
    bronze = require "turf.open.floor.bronze.mod",
    sepia = require "turf.open.floor.sepia.mod",
    bluespace = require "turf.open.floor.bluespace.mod",
    clockwork = require "turf.open.floor.clockwork.mod",
    oldshuttle = require "turf.open.floor.oldshuttle.mod",
    noslip = require "turf.open.floor.noslip.mod",
    pod = require "turf.open.floor.pod.mod",
    circuit = require "turf.open.floor.circuit.mod",
    vault = require "turf.open.floor.vault.mod",
    goonplaque = require "turf.open.floor.goonplaque.mod",
    mineral = require "turf.open.floor.mineral.mod",
    light = require "turf.open.floor.light.mod",
    fakespace = require "turf.open.floor.fakespace.mod",
    fakepit = require "turf.open.floor.fakepit.mod",
    carpet = require "turf.open.floor.carpet.mod",
    grass = require "turf.open.floor.grass.mod",
    wood = require "turf.open.floor.wood.mod",
    plating = require "turf.open.floor.plating.mod",
    mech_bay_recharge_floor = require "turf.open.floor.mech_bay_recharge_floor.mod",
}
