local Asteroid = require "mob/living/simple_animal/hostile/asteroid/class"
local Goldgrub = Asteroid:new{
    name = "goldgrub",
    desc = "A worm that grows fat from eating everything in its sight. Seems to enjoy precious metals and other shiny things, hence the name.",
    icon = 'icons/mob/lavaland/lavaland_monsters.dmi',
    icon_state = "Goldgrub",
    icon_living = "Goldgrub",
    icon_aggro = "Goldgrub_alert",
    icon_dead = "Goldgrub_dead",
    icon_gib = "syndicate_gib",
    mob_biotypes = {"organic", "beast", },
    vision_range = 2,
    aggro_vision_range = 9,
    move_to_delay = 5,
    friendly = "harmlessly rolls into",
    maxHealth = 45,
    health = 45,
    harm_intent_damage = 5,
    melee_damage_lower = 0,
    melee_damage_upper = 0,
    attacktext = "barrels into",
    attack_sound = 'sound/weapons/punch1.ogg',
    a_intent = "help",
    speak_emote = {"screeches", },
    throw_message = "sinks in slowly, before being pushed out of ",
    deathmessage = "spits up the contents of its stomach before dying!",
    status_flags = 8,
    search_objects = 1,
    wanted_objects = {nil, nil, nil, nil, },
    chase_time = 100,
    will_burrow = 1,

}
return Goldgrub
