local Self = require "datum.hallucination.class"
return {
    CLASS = Self,
    stray_bullet = require "datum.hallucination.stray_bullet.mod",
    husks = require "datum.hallucination.husks.mod",
    shock = require "datum.hallucination.shock.mod",
    fire = require "datum.hallucination.fire.mod",
    death = require "datum.hallucination.death.mod",
    dangerflash = require "datum.hallucination.dangerflash.mod",
    items = require "datum.hallucination.items.mod",
    fake_alert = require "datum.hallucination.fake_alert.mod",
    hudscrew = require "datum.hallucination.hudscrew.mod",
    stationmessage = require "datum.hallucination.stationmessage.mod",
    weird_sounds = require "datum.hallucination.weird_sounds.mod",
    sounds = require "datum.hallucination.sounds.mod",
    message = require "datum.hallucination.message.mod",
    chat = require "datum.hallucination.chat.mod",
    bolts = require "datum.hallucination.bolts.mod",
    self_delusion = require "datum.hallucination.self_delusion.mod",
    delusion = require "datum.hallucination.delusion.mod",
    items_other = require "datum.hallucination.items_other.mod",
    battle = require "datum.hallucination.battle.mod",
    oh_yeah = require "datum.hallucination.oh_yeah.mod",
    xeno_attack = require "datum.hallucination.xeno_attack.mod",
    fake_flood = require "datum.hallucination.fake_flood.mod",
}
