local Self = require "datum.status_effect.stabilized.class"
return {
    CLASS = Self,
    rainbow = require "datum.status_effect.stabilized.rainbow.mod",
    gold = require "datum.status_effect.stabilized.gold.mod",
    adamantine = require "datum.status_effect.stabilized.adamantine.mod",
    lightpink = require "datum.status_effect.stabilized.lightpink.mod",
    black = require "datum.status_effect.stabilized.black.mod",
    oil = require "datum.status_effect.stabilized.oil.mod",
    pink = require "datum.status_effect.stabilized.pink.mod",
    green = require "datum.status_effect.stabilized.green.mod",
    red = require "datum.status_effect.stabilized.red.mod",
    pyrite = require "datum.status_effect.stabilized.pyrite.mod",
    cerulean = require "datum.status_effect.stabilized.cerulean.mod",
    sepia = require "datum.status_effect.stabilized.sepia.mod",
    bluespace = require "datum.status_effect.stabilized.bluespace.mod",
    silver = require "datum.status_effect.stabilized.silver.mod",
    darkblue = require "datum.status_effect.stabilized.darkblue.mod",
    darkpurple = require "datum.status_effect.stabilized.darkpurple.mod",
    yellow = require "datum.status_effect.stabilized.yellow.mod",
    metal = require "datum.status_effect.stabilized.metal.mod",
    blue = require "datum.status_effect.stabilized.blue.mod",
    purple = require "datum.status_effect.stabilized.purple.mod",
    orange = require "datum.status_effect.stabilized.orange.mod",
    grey = require "datum.status_effect.stabilized.grey.mod",
    null = require "datum.status_effect.stabilized.null.mod",
}
