local Megafauna = require "mob/living/simple_animal/hostile/megafauna/class"
local Dragon = Megafauna:new{
    name = "ash drake",
    desc = "Guardians of the necropolis.",
    health = 2500,
    maxHealth = 2500,
    spacewalk = 1,
    attacktext = "chomps",
    attack_sound = 'sound/magic/demon_attack1.ogg',
    icon = 'icons/mob/lavaland/64x64megafauna.dmi',
    icon_state = "dragon",
    icon_living = "dragon",
    icon_dead = "dragon_dead",
    friendly = "stares down",
    speak_emote = {"roars", },
    armour_penetration = 40,
    melee_damage_lower = 40,
    melee_damage_upper = 40,
    speed = 1,
    move_to_delay = 5,
    ranged = 1,
    pixel_x = -16,
    crusher_loot = {nil, },
    loot = {nil, },
    butcher_results = {nil, nil, nil, },
    guaranteed_butcher_results = {nil, },
    swooping = 0,
    player_cooldown = 0,
    internal_type = nil,
    medal_type = "Drake",
    score_type = "Drakes Killed",
    deathmessage = "collapses into a pile of bones, its flesh sloughing away.",
    deathsound = 'sound/magic/demon_dies.ogg',
    smallsprite = nil,
    do_footstep = 1,

}
return Dragon
