local Self = require "datum.objective_item.steal.class"
return {
    CLASS = Self,
    slime = require "datum.objective_item.steal.slime.mod",
    blueprints = require "datum.objective_item.steal.blueprints.mod",
    functionalai = require "datum.objective_item.steal.functionalai.mod",
    plasma = require "datum.objective_item.steal.plasma.mod",
    supermatter = require "datum.objective_item.steal.supermatter.mod",
    nuke_core = require "datum.objective_item.steal.nuke_core.mod",
    documents = require "datum.objective_item.steal.documents.mod",
    reactive = require "datum.objective_item.steal.reactive.mod",
    reflector = require "datum.objective_item.steal.reflector.mod",
    nukedisc = require "datum.objective_item.steal.nukedisc.mod",
    hypo = require "datum.objective_item.steal.hypo.mod",
    capmedal = require "datum.objective_item.steal.capmedal.mod",
    magboots = require "datum.objective_item.steal.magboots.mod",
    jetpack = require "datum.objective_item.steal.jetpack.mod",
    handtele = require "datum.objective_item.steal.handtele.mod",
    hoslaser = require "datum.objective_item.steal.hoslaser.mod",
    caplaser = require "datum.objective_item.steal.caplaser.mod",
}
