local Asteroid = require "mob/living/simple_animal/hostile/asteroid/class"
local Fugu = Asteroid:new{
    name = "wumborian fugu",
    desc = "The wumborian fugu rapidly increases its body mass in order to ward off its prey. Great care should be taken to avoid it while it's in this state as it is nearly invincible, but it cannot maintain its form forever.",
    icon = 'icons/mob/lavaland/64x64megafauna.dmi',
    icon_state = "Fugu0",
    icon_living = "Fugu0",
    icon_aggro = "Fugu0",
    icon_dead = "Fugu_dead",
    icon_gib = "syndicate_gib",
    mob_biotypes = {"organic", "beast", },
    mouse_opacity = 1,
    move_to_delay = 5,
    friendly = "floats near",
    speak_emote = {"puffs", },
    vision_range = 5,
    speed = 0,
    maxHealth = 50,
    health = 50,
    pixel_x = -16,
    harm_intent_damage = 5,
    obj_damage = 0,
    melee_damage_lower = 0,
    melee_damage_upper = 0,
    attacktext = "chomps",
    attack_sound = 'sound/weapons/punch1.ogg',
    throw_message = "is avoided by the",
    aggro_vision_range = 9,
    mob_size = 1,
    environment_smash = 0,
    gold_core_spawnable = 1,
    wumbo = 0,
    inflate_cooldown = 0,
    E = nil,
    loot = {nil, },

}
return Fugu
