local SimpleAnimal = require "mob/living/simple_animal/class"
local Imp = SimpleAnimal:new{
    name = "imp",
    real_name = "imp",
    unique_name = 1,
    desc = "A large, menacing creature covered in armored black scales.",
    speak_emote = {"cackles", },
    emote_hear = {"cackles", "screeches", },
    response_help = "thinks better of touching",
    response_disarm = "flails at",
    response_harm = "punches",
    icon = 'icons/mob/mob.dmi',
    icon_state = "imp",
    icon_living = "imp",
    mob_biotypes = {"organic", "humanoid", },
    speed = 1,
    a_intent = "harm",
    stop_automated_movement = 1,
    status_flags = 8,
    attack_sound = 'sound/magic/demon_attack1.ogg',
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 250,
    maxbodytemp = 10000000000000000000000000000000,
    faction = {"hell", },
    attacktext = "wildly tears into",
    maxHealth = 200,
    health = 200,
    healable = 0,
    environment_smash = 1,
    obj_damage = 40,
    melee_damage_lower = 10,
    melee_damage_upper = 15,
    see_in_dark = 8,
    lighting_alpha = 128,
    boost = 0,
    bloodcrawl = 2,
    consumed_mobs = {},
    playstyle_string = "<span class='big bold'>You are an imp,</span><B> a mischievous creature from hell. You are the lowest rank on the hellish totem pole  Though you are not obligated to help, perhaps by aiding a higher ranking devil, you might just get a promotion.  However, you are incapable	of intentionally harming a fellow devil.</B>",

}
return Imp
