local Self = require "datum.dog_fashion.head.class"
return {
    CLASS = Self,
    clown = require "datum.dog_fashion.head.clown.mod",
    deathsquad = require "datum.dog_fashion.head.deathsquad.mod",
    hop = require "datum.dog_fashion.head.hop.mod",
    sombrero = require "datum.dog_fashion.head.sombrero.mod",
    reindeer = require "datum.dog_fashion.head.reindeer.mod",
    cargo_tech = require "datum.dog_fashion.head.cargo_tech.mod",
    santa = require "datum.dog_fashion.head.santa.mod",
    ghost = require "datum.dog_fashion.head.ghost.mod",
    cardborg = require "datum.dog_fashion.head.cardborg.mod",
    red_wizard = require "datum.dog_fashion.head.red_wizard.mod",
    blue_wizard = require "datum.dog_fashion.head.blue_wizard.mod",
    warden = require "datum.dog_fashion.head.warden.mod",
    ushanka = require "datum.dog_fashion.head.ushanka.mod",
    pirate = require "datum.dog_fashion.head.pirate.mod",
    nurse = require "datum.dog_fashion.head.nurse.mod",
    detective = require "datum.dog_fashion.head.detective.mod",
    beret = require "datum.dog_fashion.head.beret.mod",
    rabbit = require "datum.dog_fashion.head.rabbit.mod",
    kitty = require "datum.dog_fashion.head.kitty.mod",
    captain = require "datum.dog_fashion.head.captain.mod",
    chef = require "datum.dog_fashion.head.chef.mod",
    helmet = require "datum.dog_fashion.head.helmet.mod",
}
