local Self = require "turf.open.floor.plasteel.class"
return {
    CLASS = Self,
    shuttle = require "turf.open.floor.plasteel.shuttle.mod",
    sepia = require "turf.open.floor.plasteel.sepia.mod",
    bluespace = require "turf.open.floor.plasteel.bluespace.mod",
    elevatorshaft = require "turf.open.floor.plasteel.elevatorshaft.mod",
    rockvault = require "turf.open.floor.plasteel.rockvault.mod",
    stairs = require "turf.open.floor.plasteel.stairs.mod",
    goonplaque = require "turf.open.floor.plasteel.goonplaque.mod",
    vaporwave = require "turf.open.floor.plasteel.vaporwave.mod",
    cult = require "turf.open.floor.plasteel.cult.mod",
    cafeteria = require "turf.open.floor.plasteel.cafeteria.mod",
    grimy = require "turf.open.floor.plasteel.grimy.mod",
    kitchen_coldroom = require "turf.open.floor.plasteel.kitchen_coldroom.mod",
    freezer = require "turf.open.floor.plasteel.freezer.mod",
    solarpanel = require "turf.open.floor.plasteel.solarpanel.mod",
    showroomfloor = require "turf.open.floor.plasteel.showroomfloor.mod",
    chapel = require "turf.open.floor.plasteel.chapel.mod",
    recharge_floor = require "turf.open.floor.plasteel.recharge_floor.mod",
    yellowsiding = require "turf.open.floor.plasteel.yellowsiding.mod",
    white = require "turf.open.floor.plasteel.white.mod",
    checker = require "turf.open.floor.plasteel.checker.mod",
    dark = require "turf.open.floor.plasteel.dark.mod",
    telecomms = require "turf.open.floor.plasteel.telecomms.mod",
    airless = require "turf.open.floor.plasteel.airless.mod",
}
