local Self = require "datum.disease_ability.symptom.medium.class"
return {
    CLASS = Self,
    itching = require "datum.disease_ability.symptom.medium.itching.mod",
    revitiligo = require "datum.disease_ability.symptom.medium.revitiligo.mod",
    vitiligo = require "datum.disease_ability.symptom.medium.vitiligo.mod",
    viralevolution = require "datum.disease_ability.symptom.medium.viralevolution.mod",
    viraladaptation = require "datum.disease_ability.symptom.medium.viraladaptation.mod",
    nano_destroy = require "datum.disease_ability.symptom.medium.nano_destroy.mod",
    nano_boost = require "datum.disease_ability.symptom.medium.nano_boost.mod",
    headache = require "datum.disease_ability.symptom.medium.headache.mod",
    shivering = require "datum.disease_ability.symptom.medium.shivering.mod",
    fever = require "datum.disease_ability.symptom.medium.fever.mod",
    deafness = require "datum.disease_ability.symptom.medium.deafness.mod",
    visionloss = require "datum.disease_ability.symptom.medium.visionloss.mod",
    voice_change = require "datum.disease_ability.symptom.medium.voice_change.mod",
    vomit = require "datum.disease_ability.symptom.medium.vomit.mod",
    youth = require "datum.disease_ability.symptom.medium.youth.mod",
    confusion = require "datum.disease_ability.symptom.medium.confusion.mod",
    choking = require "datum.disease_ability.symptom.medium.choking.mod",
    hallucigen = require "datum.disease_ability.symptom.medium.hallucigen.mod",
    beard = require "datum.disease_ability.symptom.medium.beard.mod",
    shedding = require "datum.disease_ability.symptom.medium.shedding.mod",
    heal = require "datum.disease_ability.symptom.medium.heal.mod",
}
