local Self = require "datum.supply_pack.security.armory.class"
return {
    CLASS = Self,
    wt550ammo_single = require "datum.supply_pack.security.armory.wt550ammo_single.mod",
    wt550ammo = require "datum.supply_pack.security.armory.wt550ammo.mod",
    wt550 = require "datum.supply_pack.security.armory.wt550.mod",
    wt550_single = require "datum.supply_pack.security.armory.wt550_single.mod",
    swat = require "datum.supply_pack.security.armory.swat.mod",
    russian = require "datum.supply_pack.security.armory.russian.mod",
    riotshields = require "datum.supply_pack.security.armory.riotshields.mod",
    riothelmets = require "datum.supply_pack.security.armory.riothelmets.mod",
    riotarmor = require "datum.supply_pack.security.armory.riotarmor.mod",
    laserarmor = require "datum.supply_pack.security.armory.laserarmor.mod",
    trackingimp = require "datum.supply_pack.security.armory.trackingimp.mod",
    mindshield = require "datum.supply_pack.security.armory.mindshield.mod",
    fire = require "datum.supply_pack.security.armory.fire.mod",
    exileimp = require "datum.supply_pack.security.armory.exileimp.mod",
    energy = require "datum.supply_pack.security.armory.energy.mod",
    energy_single = require "datum.supply_pack.security.armory.energy_single.mod",
    dragnet = require "datum.supply_pack.security.armory.dragnet.mod",
    ballistic = require "datum.supply_pack.security.armory.ballistic.mod",
    ballistic_single = require "datum.supply_pack.security.armory.ballistic_single.mod",
    combatknives = require "datum.supply_pack.security.armory.combatknives.mod",
    combatknives_single = require "datum.supply_pack.security.armory.combatknives_single.mod",
    chemimp = require "datum.supply_pack.security.armory.chemimp.mod",
    bulletarmor = require "datum.supply_pack.security.armory.bulletarmor.mod",
}
