local Self = require "mob.living.carbon.human.species.class"
return {
    CLASS = Self,
    zombie = require "mob.living.carbon.human.species.zombie.mod",
    vampire = require "mob.living.carbon.human.species.vampire.mod",
    synth = require "mob.living.carbon.human.species.synth.mod",
    skeleton = require "mob.living.carbon.human.species.skeleton.mod",
    shadow = require "mob.living.carbon.human.species.shadow.mod",
    pod = require "mob.living.carbon.human.species.pod.mod",
    plasma = require "mob.living.carbon.human.species.plasma.mod",
    mush = require "mob.living.carbon.human.species.mush.mod",
    moth = require "mob.living.carbon.human.species.moth.mod",
    ethereal = require "mob.living.carbon.human.species.ethereal.mod",
    lizard = require "mob.living.carbon.human.species.lizard.mod",
    jelly = require "mob.living.carbon.human.species.jelly.mod",
    golem = require "mob.living.carbon.human.species.golem.mod",
    fly = require "mob.living.carbon.human.species.fly.mod",
    felinid = require "mob.living.carbon.human.species.felinid.mod",
    dullahan = require "mob.living.carbon.human.species.dullahan.mod",
    corporate = require "mob.living.carbon.human.species.corporate.mod",
    angel = require "mob.living.carbon.human.species.angel.mod",
    android = require "mob.living.carbon.human.species.android.mod",
    abductor = require "mob.living.carbon.human.species.abductor.mod",
}
