local Datum = require "datum/class"
local Hud = Datum:new{
    mymob = nil,
    hud_shown = 1,
    hud_version = 1,
    inventory_shown = 0,
    hotkey_ui_hidden = 0,
    lingchemdisplay = nil,
    lingstingdisplay = nil,
    blobpwrdisplay = nil,
    alien_plasma_display = nil,
    alien_queen_finder = nil,
    devilsouldisplay = nil,
    action_intent = nil,
    zone_select = nil,
    pull_icon = nil,
    rest_icon = nil,
    throw_icon = nil,
    module_store_icon = nil,
    static_inventory = {},
    toggleable_inventory = {},
    hotkeybuttons = {},
    infodisplay = {},
    screenoverlays = {},
    inv_slots = nil,
    hand_slots = nil,
    plane_masters = {},
    hide_actions_toggle = nil,
    action_buttons_hidden = 0,
    healths = nil,
    healthdoll = nil,
    internals = nil,
    ui_style = nil,

}
return Hud
