local Hostile = require "mob/living/simple_animal/hostile/class"
local MiningDrone = Hostile:new{
    name = "nanotrasen minebot",
    desc = "The instructions printed on the side read: This is a small robot used to support miners, can be set to search and collect loose ore, or to help fend off wildlife.",
    gender = "neuter",
    icon = 'icons/mob/aibots.dmi',
    icon_state = "mining_drone",
    icon_living = "mining_drone",
    status_flags = 11,
    mouse_opacity = 1,
    faction = {"neutral", },
    a_intent = "harm",
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 0,
    move_to_delay = 10,
    health = 125,
    maxHealth = 125,
    melee_damage_lower = 15,
    melee_damage_upper = 15,
    obj_damage = 10,
    environment_smash = 0,
    check_friendly_fire = 1,
    stop_automated_movement_when_pulled = 1,
    attacktext = "drills",
    attack_sound = 'sound/weapons/circsawhit.ogg',
    sentience_type = 4,
    speak_emote = {"states", },
    wanted_objects = {nil, nil, nil, nil, nil, nil, nil, nil, },
    healable = 0,
    loot = {nil, },
    del_on_death = 1,
    mode = 1,
    light_on = 0,
    stored_gun = nil,

}
return MiningDrone
