local Bot = require "mob/living/simple_animal/bot/class"
local Floorbot = Bot:new{
    name = [[\improper Floorbot]],
    desc = "A little floor repairing robot, he looks so excited!",
    icon = 'icons/mob/aibots.dmi',
    icon_state = "floorbot0",
    density = false,
    anchored = 0,
    health = 25,
    maxHealth = 25,
    spacewalk = 1,
    radio_key = nil,
    radio_channel = "Engineering",
    bot_type = 4,
    model = "Floorbot",
    bot_core = nil,
    window_id = "autofloor",
    window_name = "Automatic Station Floor Repairer v1.1",
    path_image_color = "#FFA500",
    process_type = nil,
    targetdirection = nil,
    replacetiles = 0,
    placetiles = 0,
    specialtiles = 0,
    maxtiles = 100,
    tiletype = nil,
    fixfloors = 1,
    autotile = 0,
    max_targets = 50,
    target = nil,
    oldloc = nil,
    toolbox = nil,
    toolbox_color = "",

}
return Floorbot
