local Self = require "datum.sprite_accessory.socks.class"
return {
    CLASS = Self,
    white_thigh = require "datum.sprite_accessory.socks.white_thigh.mod",
    uk_thigh = require "datum.sprite_accessory.socks.uk_thigh.mod",
    thin_thigh = require "datum.sprite_accessory.socks.thin_thigh.mod",
    striped_thigh = require "datum.sprite_accessory.socks.striped_thigh.mod",
    rainbow_thigh = require "datum.sprite_accessory.socks.rainbow_thigh.mod",
    usa_thigh = require "datum.sprite_accessory.socks.usa_thigh.mod",
    commie_thigh = require "datum.sprite_accessory.socks.commie_thigh.mod",
    black_thigh = require "datum.sprite_accessory.socks.black_thigh.mod",
    white_short = require "datum.sprite_accessory.socks.white_short.mod",
    black_short = require "datum.sprite_accessory.socks.black_short.mod",
    pantyhose = require "datum.sprite_accessory.socks.pantyhose.mod",
    white_norm = require "datum.sprite_accessory.socks.white_norm.mod",
    black_norm = require "datum.sprite_accessory.socks.black_norm.mod",
    white_knee = require "datum.sprite_accessory.socks.white_knee.mod",
    uk_knee = require "datum.sprite_accessory.socks.uk_knee.mod",
    thin_knee = require "datum.sprite_accessory.socks.thin_knee.mod",
    striped_knee = require "datum.sprite_accessory.socks.striped_knee.mod",
    rainbow_knee = require "datum.sprite_accessory.socks.rainbow_knee.mod",
    usa_knee = require "datum.sprite_accessory.socks.usa_knee.mod",
    commie_knee = require "datum.sprite_accessory.socks.commie_knee.mod",
    black_knee = require "datum.sprite_accessory.socks.black_knee.mod",
    nude = require "datum.sprite_accessory.socks.nude.mod",
}
