local Hostile = require "mob/living/simple_animal/hostile/class"
local Faithless = Hostile:new{
    name = "The Faithless",
    desc = "The Wish Granter's faith in humanity, incarnate.",
    icon_state = "faithless",
    icon_living = "faithless",
    icon_dead = "faithless_dead",
    mob_biotypes = {"organic", "humanoid", },
    gender = "male",
    speak_chance = 0,
    turns_per_move = 5,
    response_help = "passes through",
    response_disarm = "shoves",
    response_harm = "hits",
    emote_taunt = {"wails", },
    taunt_chance = 25,
    speed = 0,
    maxHealth = 80,
    health = 80,
    spacewalk = 1,
    stat_attack = 2,
    robust_searching = 1,
    harm_intent_damage = 10,
    obj_damage = 50,
    melee_damage_lower = 15,
    melee_damage_upper = 15,
    attacktext = "grips",
    attack_sound = 'sound/hallucinations/growl1.ogg',
    speak_emote = {"growls", },
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    minbodytemp = 0,
    faction = {"faithless", },
    gold_core_spawnable = 1,
    do_footstep = 1,

}
return Faithless
