local Self = require "area.holodeck.rec_center.class"
return {
    CLASS = Self,
    thunderdome1218 = require "area.holodeck.rec_center.thunderdome1218.mod",
    refuel = require "area.holodeck.rec_center.refuel.mod",
    anthophila = require "area.holodeck.rec_center.anthophila.mod",
    bunker = require "area.holodeck.rec_center.bunker.mod",
    wildlife = require "area.holodeck.rec_center.wildlife.mod",
    burn = require "area.holodeck.rec_center.burn.mod",
    photobooth = require "area.holodeck.rec_center.photobooth.mod",
    winterwonderland = require "area.holodeck.rec_center.winterwonderland.mod",
    kobayashi = require "area.holodeck.rec_center.kobayashi.mod",
    spacechess = require "area.holodeck.rec_center.spacechess.mod",
    chapelcourt = require "area.holodeck.rec_center.chapelcourt.mod",
    school = require "area.holodeck.rec_center.school.mod",
    firingrange = require "area.holodeck.rec_center.firingrange.mod",
    pet_lounge = require "area.holodeck.rec_center.pet_lounge.mod",
    medical = require "area.holodeck.rec_center.medical.mod",
    lounge = require "area.holodeck.rec_center.lounge.mod",
    beach = require "area.holodeck.rec_center.beach.mod",
    thunderdome = require "area.holodeck.rec_center.thunderdome.mod",
    basketball = require "area.holodeck.rec_center.basketball.mod",
    dodgeball = require "area.holodeck.rec_center.dodgeball.mod",
    court = require "area.holodeck.rec_center.court.mod",
    offline = require "area.holodeck.rec_center.offline.mod",
}
