local Self = require "datum.uplink_item.explosives.class"
return {
    CLASS = Self,
    viscerators = require "datum.uplink_item.explosives.viscerators.mod",
    tearstache = require "datum.uplink_item.explosives.tearstache.mod",
    syndicate_minibomb = require "datum.uplink_item.explosives.syndicate_minibomb.mod",
    syndicate_detonator = require "datum.uplink_item.explosives.syndicate_detonator.mod",
    syndicate_bomb = require "datum.uplink_item.explosives.syndicate_bomb.mod",
    soap_clusterbang = require "datum.uplink_item.explosives.soap_clusterbang.mod",
    pizza_bomb = require "datum.uplink_item.explosives.pizza_bomb.mod",
    grenadier = require "datum.uplink_item.explosives.grenadier.mod",
    virus_grenade = require "datum.uplink_item.explosives.virus_grenade.mod",
    emp = require "datum.uplink_item.explosives.emp.mod",
    detomatix = require "datum.uplink_item.explosives.detomatix.mod",
    clown_bomb_clownops = require "datum.uplink_item.explosives.clown_bomb_clownops.mod",
    x4bag = require "datum.uplink_item.explosives.x4bag.mod",
    c4bag = require "datum.uplink_item.explosives.c4bag.mod",
    c4 = require "datum.uplink_item.explosives.c4.mod",
    buzzkill = require "datum.uplink_item.explosives.buzzkill.mod",
    bombanana = require "datum.uplink_item.explosives.bombanana.mod",
    bioterrorfoam = require "datum.uplink_item.explosives.bioterrorfoam.mod",
}
