local Datum = require "datum/class"
local Image = Datum:new{
    alpha = nil,
    appearance = nil,
    appearance_flags = nil,
    blend_mode = nil,
    color = nil,
    icon = nil,
    icon_state = nil,
    text = nil,
    dir = nil,
    underlays = nil,
    overlays = nil,
    loc = nil,
    layer = 5,
    maptext = nil,
    maptext_width = nil,
    maptext_height = nil,
    maptext_x = nil,
    maptext_y = nil,
    pixel_x = nil,
    pixel_y = nil,
    pixel_w = nil,
    pixel_z = nil,
    plane = nil,
    x = nil,
    y = nil,
    z = nil,
    override = nil,
    transform = nil,
    vis_contents = nil,
    filters = nil,
    name = nil,
    mouse_opacity = nil,

}
return Image
