local Bot = require "mob/living/simple_animal/bot/class"
local Secbot = Bot:new{
    name = [[\improper Securitron]],
    desc = "A little security robot.  He looks less than thrilled.",
    icon = 'icons/mob/aibots.dmi',
    icon_state = "secbot",
    density = false,
    anchored = 0,
    health = 25,
    maxHealth = 25,
    damage_coeff = {"brute", "fire", "tox", "clone", "stamina", "oxy", },
    pass_flags = 16,
    radio_key = nil,
    radio_channel = "Security",
    bot_type = 1,
    model = "Securitron",
    bot_core_type = nil,
    window_id = "autosec",
    window_name = "Automatic Security Unit v1.6",
    allow_pai = 0,
    data_hud_type = 2,
    path_image_color = "#FF0000",
    baton_type = nil,
    target = nil,
    oldtarget_name = nil,
    threatlevel = 0,
    target_lastloc = nil,
    last_found = nil,
    declare_arrests = 1,
    idcheck = 0,
    weaponscheck = 0,
    check_records = 1,
    arrest_type = 0,

}
return Secbot
