local Atom = require "atom/class"
local Turf = Atom:new{
    parent_type = nil,
    layer = 2,
    vis_contents = nil,
    vis_locs = nil,
    fixed_underlay = nil,
    icon = 'icons/turf/floors.dmi',
    level = 1,
    intact = 1,
    baseturfs = nil,
    temperature = 293.15,
    to_be_destroyed = 0,
    max_fire_temperature_sustained = 0,
    blocks_air = 0,
    flags_1 = 4,
    blueprint_data = nil,
    explosion_level = 0,
    explosion_id = 0,
    requires_activation = nil,
    changing_turf = 0,
    bullet_bounce_sound = 'sound/weapons/bulletremove.ogg',
    bullet_sizzle = 0,
    tiled_dirt = 0,
    CanAtmosPass = 0,
    CanAtmosPassVertical = 0,
    thermal_conductivity = 0.05,
    heat_capacity = 1,
    temperature_archived = nil,
    atmos_adjacent_turfs = nil,
    atmos_supeconductivity = 0,
    archived_cycle = 0,
    current_cycle = 0,
    initial_gas_mix = "o2=22;n2=82;TEMP=293.15",
    dynamic_lighting = 1,
    luminosity = 1,
    lighting_corners_initialised = nil,
    affecting_lights = nil,
    lighting_object = nil,
    corners = nil,
    has_opaque_atom = nil,

}
return Turf
