local Self = require "datum.bounty.item.chef.class"
return {
    CLASS = Self,
    nuggies = require "datum.bounty.item.chef.nuggies.mod",
    pancakes = require "datum.bounty.item.chef.pancakes.mod",
    soylentgreen = require "datum.bounty.item.chef.soylentgreen.mod",
    kebab = require "datum.bounty.item.chef.kebab.mod",
    chawanmushi = require "datum.bounty.item.chef.chawanmushi.mod",
    muffin = require "datum.bounty.item.chef.muffin.mod",
    eggplantparm = require "datum.bounty.item.chef.eggplantparm.mod",
    hotdog = require "datum.bounty.item.chef.hotdog.mod",
    cubancarp = require "datum.bounty.item.chef.cubancarp.mod",
    poppypretzel = require "datum.bounty.item.chef.poppypretzel.mod",
    superbite = require "datum.bounty.item.chef.superbite.mod",
    carrotfries = require "datum.bounty.item.chef.carrotfries.mod",
    salad = require "datum.bounty.item.chef.salad.mod",
    pie = require "datum.bounty.item.chef.pie.mod",
    bread = require "datum.bounty.item.chef.bread.mod",
    icecreamsandwich = require "datum.bounty.item.chef.icecreamsandwich.mod",
    onionrings = require "datum.bounty.item.chef.onionrings.mod",
    popcorn = require "datum.bounty.item.chef.popcorn.mod",
    soup = require "datum.bounty.item.chef.soup.mod",
    birthday_cake = require "datum.bounty.item.chef.birthday_cake.mod",
}
