local Component = require "datum/component/class"
local Storage = Component:new{
    dupe_mode = 2,
    master = nil,
    can_hold = nil,
    cant_hold = nil,
    exception_hold = nil,
    is_using = nil,
    locked = 0,
    max_w_class = 2,
    max_combined_w_class = 14,
    max_items = 7,
    emp_shielded = 0,
    silent = 0,
    click_gather = 0,
    rustle_sound = 1,
    allow_quick_empty = 0,
    allow_quick_gather = 0,
    collection_mode = 1,
    insert_preposition = "in",
    display_numerical_stacking = 0,
    boxes = nil,
    closer = nil,
    allow_big_nesting = 0,
    attack_hand_interact = 1,
    quickdraw = 0,
    modeswitch_action = nil,
    screen_max_columns = 7,
    screen_max_rows = 10000000000000000000000000000000,
    screen_pixel_x = 16,
    screen_pixel_y = 16,
    screen_start_x = 4,
    screen_start_y = 2,

}
return Storage
