local Self = require "datum.uplink_item.dangerous.class"
return {
    CLASS = Self,
    foampistol = require "datum.uplink_item.dangerous.foampistol.mod",
    foammachinegun = require "datum.uplink_item.dangerous.foammachinegun.mod",
    foamsmg = require "datum.uplink_item.dangerous.foamsmg.mod",
    revolver = require "datum.uplink_item.dangerous.revolver.mod",
    bolt_action = require "datum.uplink_item.dangerous.bolt_action.mod",
    pistol = require "datum.uplink_item.dangerous.pistol.mod",
    sniper = require "datum.uplink_item.dangerous.sniper.mod",
    powerfist = require "datum.uplink_item.dangerous.powerfist.mod",
    carbine = require "datum.uplink_item.dangerous.carbine.mod",
    machinegun = require "datum.uplink_item.dangerous.machinegun.mod",
    guardian = require "datum.uplink_item.dangerous.guardian.mod",
    rapid = require "datum.uplink_item.dangerous.rapid.mod",
    flamethrower = require "datum.uplink_item.dangerous.flamethrower.mod",
    shield = require "datum.uplink_item.dangerous.shield.mod",
    sword = require "datum.uplink_item.dangerous.sword.mod",
    doublesword = require "datum.uplink_item.dangerous.doublesword.mod",
    smg = require "datum.uplink_item.dangerous.smg.mod",
    shotgun = require "datum.uplink_item.dangerous.shotgun.mod",
    throwingweapons = require "datum.uplink_item.dangerous.throwingweapons.mod",
    bioterror = require "datum.uplink_item.dangerous.bioterror.mod",
    clownsword = require "datum.uplink_item.dangerous.clownsword.mod",
    bananashield = require "datum.uplink_item.dangerous.bananashield.mod",
    pie_cannon = require "datum.uplink_item.dangerous.pie_cannon.mod",
    rawketlawnchair = require "datum.uplink_item.dangerous.rawketlawnchair.mod",
}
