local Datum = require "datum/class"
local Atom = Datum:new{
    parent_type = nil,
    alpha = nil,
    appearance = nil,
    appearance_flags = nil,
    blend_mode = nil,
    color = nil,
    contents = nil,
    density = false,
    desc = nil,
    dir = nil,
    gender = nil,
    icon = nil,
    icon_state = nil,
    invisibility = nil,
    infra_luminosity = nil,
    loc = nil,
    layer = 2,
    luminosity = nil,
    maptext = nil,
    maptext_width = nil,
    maptext_height = nil,
    maptext_x = nil,
    maptext_y = nil,
    mouse_over_pointer = nil,
    mouse_drag_pointer = nil,
    mouse_drop_pointer = nil,
    mouse_drop_zone = nil,
    mouse_opacity = nil,
    name = nil,
    opacity = false,
    overlays = nil,
    pixel_x = nil,
    pixel_y = nil,
    pixel_w = nil,
    pixel_z = nil,
    plane = -1,
    suffix = nil,
    text = nil,
    transform = nil,
    underlays = nil,
    verbs = nil,
    x = nil,
    y = nil,
    z = nil,
    filters = nil,
    smooth = 0,
    top_left_corner = nil,
    top_right_corner = nil,
    bottom_left_corner = nil,
    bottom_right_corner = nil,
    canSmoothWith = nil,
    wires = nil,
    alternate_appearances = nil,
    level = 2,
    article = nil,
    flags_1 = 0,
    interaction_flags_atom = 0,
    reagents = nil,
    hud_list = nil,
    hud_possible = nil,
    explosion_block = 0,
    atom_colours = nil,
    priority_overlays = nil,
    remove_overlays = nil,
    add_overlays = nil,
    managed_vis_overlays = nil,
    proximity_monitor = nil,
    buckle_message_cooldown = 0,
    fingerprintslast = nil,
    filter_data = nil,
    custom_price = nil,
    custom_premium_price = nil,
    orbiters = nil,
    rad_flags = 0,
    rad_insulation = 1,
    CanAtmosPass = 1,
    CanAtmosPassVertical = 1,
    light_power = 1,
    light_range = 0,
    light_color = nil,
    light = nil,
    light_sources = nil,
}

function Atom:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    if o.entity then
        o.density = WORLD:create_component(o.entity, "density", o.density)
        o.dir = WORLD:create_component(o.entity, "dir", o.dir)
        o.icon_state = WORLD:create_component(o.entity, "icon_state", o.icon_state)
        o.opacity = WORLD:create_component(o.entity, "opacity", o.opacity)
    end
    return o
end

return Atom
