local Self = require "datum.map_template.ruin.lavaland.class"
return {
    CLASS = Self,
    puzzle = require "datum.map_template.ruin.lavaland.puzzle.mod",
    miningripley = require "datum.map_template.ruin.lavaland.miningripley.mod",
    swarmer_boss = require "datum.map_template.ruin.lavaland.swarmer_boss.mod",
    hermit = require "datum.map_template.ruin.lavaland.hermit.mod",
    cultaltar = require "datum.map_template.ruin.lavaland.cultaltar.mod",
    pizza = require "datum.map_template.ruin.lavaland.pizza.mod",
    survivalcapsule = require "datum.map_template.ruin.lavaland.survivalcapsule.mod",
    fountain = require "datum.map_template.ruin.lavaland.fountain.mod",
    xeno_nest = require "datum.map_template.ruin.lavaland.xeno_nest.mod",
    ufo_crash = require "datum.map_template.ruin.lavaland.ufo_crash.mod",
    blood_drunk_miner = require "datum.map_template.ruin.lavaland.blood_drunk_miner.mod",
    hierophant = require "datum.map_template.ruin.lavaland.hierophant.mod",
    ratvar = require "datum.map_template.ruin.lavaland.ratvar.mod",
    sin = require "datum.map_template.ruin.lavaland.sin.mod",
    animal_hospital = require "datum.map_template.ruin.lavaland.animal_hospital.mod",
    free_golem = require "datum.map_template.ruin.lavaland.free_golem.mod",
    syndicate_base = require "datum.map_template.ruin.lavaland.syndicate_base.mod",
    ash_walker = require "datum.map_template.ruin.lavaland.ash_walker.mod",
    seed_vault = require "datum.map_template.ruin.lavaland.seed_vault.mod",
    cube = require "datum.map_template.ruin.lavaland.cube.mod",
    biodome = require "datum.map_template.ruin.lavaland.biodome.mod",
}
