local Datum = require "datum/class"
local Outfit = Datum:new{
    name = "Naked",
    uniform = nil,
    suit = nil,
    toggle_helmet = 1,
    back = nil,
    belt = nil,
    gloves = nil,
    shoes = nil,
    head = nil,
    mask = nil,
    neck = nil,
    ears = nil,
    glasses = nil,
    id = nil,
    l_pocket = nil,
    r_pocket = nil,
    suit_store = nil,
    r_hand = nil,
    l_hand = nil,
    internals_slot = nil,
    backpack_contents = nil,
    box = nil,
    implants = nil,
    accessory = nil,
    can_be_admin_equipped = 1,
    chameleon_extras = nil,

}
return Outfit
