local Bot = require "mob/living/simple_animal/bot/class"
local Cleanbot = Bot:new{
    name = [[\improper Cleanbot]],
    desc = "A little cleaning robot, he looks so excited!",
    icon = 'icons/mob/aibots.dmi',
    icon_state = "cleanbot0",
    density = false,
    anchored = 0,
    health = 25,
    maxHealth = 25,
    radio_key = nil,
    radio_channel = "Service",
    bot_type = 8,
    model = "Cleanbot",
    bot_core_type = nil,
    window_id = "autoclean",
    window_name = "Automatic Station Cleaner v1.2",
    pass_flags = 16,
    path_image_color = "#993299",
    blood = 1,
    trash = 0,
    pests = 0,
    drawn = 0,
    target_types = nil,
    target = nil,
    max_targets = 50,
    oldloc = nil,
    closest_dist = nil,
    closest_loc = nil,
    failed_steps = nil,
    next_dest = nil,
    next_dest_loc = nil,

}
return Cleanbot
