local Self = require "datum.round_event.wizard.class"
return {
    CLASS = Self,
    summonmagic = require "datum.round_event.wizard.summonmagic.mod",
    summonguns = require "datum.round_event.wizard.summonguns.mod",
    shuffleminds = require "datum.round_event.wizard.shuffleminds.mod",
    shufflenames = require "datum.round_event.wizard.shufflenames.mod",
    shuffleloc = require "datum.round_event.wizard.shuffleloc.mod",
    shuffle = require "datum.round_event.wizard.shuffle.mod",
    rpgloot = require "datum.round_event.wizard.rpgloot.mod",
    race = require "datum.round_event.wizard.race.mod",
    petsplosion = require "datum.round_event.wizard.petsplosion.mod",
    magicarp = require "datum.round_event.wizard.magicarp.mod",
    madness = require "datum.round_event.wizard.madness.mod",
    lava = require "datum.round_event.wizard.lava.mod",
    invincible = require "datum.round_event.wizard.invincible.mod",
    imposter = require "datum.round_event.wizard.imposter.mod",
    greentext = require "datum.round_event.wizard.greentext.mod",
    possession = require "datum.round_event.wizard.possession.mod",
    ghost = require "datum.round_event.wizard.ghost.mod",
    fake_explosion = require "datum.round_event.wizard.fake_explosion.mod",
    deprevolt = require "datum.round_event.wizard.deprevolt.mod",
    cursed_items = require "datum.round_event.wizard.cursed_items.mod",
    blobies = require "datum.round_event.wizard.blobies.mod",
    improvedcasting = require "datum.round_event.wizard.improvedcasting.mod",
    robelesscasting = require "datum.round_event.wizard.robelesscasting.mod",
}
