local Hostile = require "mob/living/simple_animal/hostile/class"
local CatButcherer = Hostile:new{
    name = "Cat Surgeon",
    desc = "A man with the quest of chasing endless feline tail.",
    icon = 'icons/mob/simple_human.dmi',
    icon_state = "cat_butcher",
    icon_living = "cat_butcher",
    icon_dead = "syndicate_dead",
    icon_gib = "syndicate_gib",
    speak_chance = 0,
    turns_per_move = 5,
    response_help = "pokes",
    response_disarm = "shoves",
    response_harm = "hits",
    speed = 0,
    stat_attack = 2,
    robust_searching = 1,
    maxHealth = 100,
    health = 100,
    harm_intent_damage = 5,
    melee_damage_lower = 15,
    melee_damage_upper = 15,
    attacktext = "slashes at",
    attack_sound = 'sound/weapons/circsawhit.ogg',
    a_intent = "harm",
    mob_biotypes = {"organic", "humanoid", },
    loot = {nil, nil, },
    atmos_requirements = {"min_oxy", "max_oxy", "min_tox", "max_tox", "min_co2", "max_co2", "min_n2", "max_n2", },
    unsuitable_atmos_damage = 15,
    faction = {"hostile", },
    check_friendly_fire = 1,
    status_flags = 8,
    del_on_death = 1,

}
return CatButcherer
